apiVersion: v1
kind: Template
parameters:
- name: PROJECT
  description: The name of the application project.
  required: true
- name: COMPONENT
  description: The name of the application component.
  required: true
- name: ODS_IMAGE_TAG
  value: latest
objects:
- apiVersion: v1
  kind: BuildConfig
  metadata:
    labels:
      app: 'ods-doc-gen-svc'
    name: ${COMPONENT}
  spec:
    nodeSelector: null
    output:
      imageLabels:
      - name: "ods.application.name"
        value: "Document Generation Service"
      to:
        kind: ImageStreamTag
        name: ${COMPONENT}:${ODS_IMAGE_TAG}
    postCommit: {}
    resources: {}
    runPolicy: Serial
    source:
      binary: {}
      type: Binary
    strategy:
      dockerStrategy: {}
      type: Docker
    triggers: []
