apiVersion: v1
kind: Template
parameters:
- name: PROJECT
  description: The name of the application project.
  required: true
- name: COMPONENT
  description: The name of the application component.
  required: true
objects:
- apiVersion: v1
  kind: ImageStream
  metadata:
    labels:
      app: 'ods-doc-gen-svc'
    name: ${COMPONENT}
  spec:
    dockerImageRepository: ${COMPONENT}
    lookupPolicy:
      local: false
