name: Document Generation Service

on: [ push, pull_request ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: download and install wkhtml 
      run: | 
        sudo apt install curl
        sudo curl -kLO https://downloads.wkhtmltopdf.org/0.12/0.12.4/wkhtmltox-0.12.4_linux-generic-amd64.tar.xz
        sudo tar vxf wkhtmltox-0.12.4_linux-generic-amd64.tar.xz
        sudo mv wkhtmltox/bin/wkhtmlto* /usr/bin
    - name: Build with Gradle
      run: ./gradlew clean test shadowJar --stacktrace --no-daemon
      env:
        NO_NEXUS: true
    - uses: actions/cache@v1
      with:
        path: ~/.gradle/caches
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
        restore-keys: |
          ${{ runner.os }}-gradle-
    - name: copy created artifacts into docker context
      run: | 
        cp build/libs/*-all.jar ./docker/app.jar
    - name: Build docker image
      if: success()
      run: docker build -t ods-document-generation-svc:local .
      working-directory: docker
    - name: Push docker image
      if: success() && github.repository == 'opendevstack/ods-document-generation-svc' && github.event_name == 'push'
      shell: bash
      env:
        DOCKER_USER: ${{ secrets.DockerHubUser }}
        DOCKER_PASS: ${{ secrets.DockerHubPass }}
      run: ./.github/workflows/push-image.sh ${{ github.ref }} "$DOCKER_USER" "$DOCKER_PASS"

